OY-2896
Opetushallitus/ehoks pull request #410
Opened 2021-11-25 13:22 UTC by samje

2021-11-25 13:29 UTC, kechpaja-at-gofore requested changes

2021-11-25 13:29 UTC, kechpaja-at-gofore commented on src/oph/ehoks/virkailija/handler.clj
> +                                     (str "User privileges does not match "
does -> do

2021-11-25 13:29 UTC, kechpaja-at-gofore commented on src/oph/ehoks/virkailija/handler.clj
> +                                                          "*ADDED*")})
Olisiko parempi palauttaa deleted_at päivämäärä tässä "*ADDED*"-stringin sijassa?

2021-11-25 13:36 UTC, samje commented on src/oph/ehoks/virkailija/handler.clj
> +                                                          "*ADDED*")})
Joo, mutta silloin pitäisi luoda erillinen haku tätä varten, jolla voidaan hakea poistettu hoks ja ottaa siihen muodostunut timestamppi. Tällä kiersin tuon ongelman. Luuletko, että olisi tarpeen tehdä tuo haku?

2021-11-25 13:43 UTC, kechpaja-at-gofore commented on src/oph/ehoks/virkailija/handler.clj
> +                                                          "*ADDED*")})
Ei ole, jos tuo shallow-delete! ei palauta sitä automaattisesti.

2021-11-25 13:46 UTC, samje commented on src/oph/ehoks/virkailija/handler.clj
> +                                                          "*ADDED*")})
Kokeilin sitä, mutta ei palauttanut mitään hyödyllistä.

2021-11-26 05:16 UTC, kechpaja-at-gofore approved these changes

2021-11-26 05:16 UTC, kechpaja-at-gofore commented on src/oph/ehoks/virkailija/handler.clj
> +                                                          "*ADDED*")})
Okei, mennään sitten sillä, mikä sulla on.

2021-11-26 12:46 UTC, merged