Require yksilöivä tunniste only in työpaikkajakso only for system transfer
Opetushallitus/ehoks pull request #550
Opened 2023-08-14 13:27 UTC by pkalliok

## Kuvaus muutoksista

Nyt on toteutettu tää niin kuin se oli määriteltykin eli yksilöiviä tunnisteita ei edellytetä muilta osaamisen hankkimistavoilta kuin työpaikkajaksoilta.

https://jira.eduuni.fi/browse/EH-1473

## Muistilista PR:n tekijälle ja katselmoijille

### Ennen asettamista katselmointiin
  - [ ] Build onnistuu ilman virheitä
  - [ ] Toiminnallisuuden kattavat yksikkötestit on tehty osana PR:ia
  - [ ] PR:n sisältämät muutokset noudattavat [sovittuja koodikäytänteitä](../doc/code-guidelines.md)
  - [ ] Koodi on riittävästi dokumentoitu tai se on muuten yksiselitteistä
  - [ ] Nimet (muuttujat, funktiot, ...) kuvaavat koodia hyvin

❗ **Katselmoijat tarkastavat, että yllä mainitut kohdat toteutuvat**

### Ennen mergeämistä `master`-haaralle
  - [ ] Vähintään yksi kehittäjä on katselmoinut ja hyväksynyt muutokset
    - Jos muutoksilla voi jotain rikkoessaan olla kauaskantoiset vaikutukset, kannattaa muutokset hyväksyttää useammalla katselmoijalla
  - [ ] Katselmoijien esittämät muutosehdotukset on huomioitu
  - [ ] Muutokset on testattu QA-ympäristössä
  - [ ] Yli jääneet kehityskohteet on tiketöity

2023-08-15 06:56 UTC, tomikat requested changes
Hyvältä näyttää, lisäsin yhden kysymyksen liittyen palautettavaan virheviestiin.

2023-08-15 06:56 UTC, tomikat commented on src/oph/ehoks/hoks/schema.clj
> +      :description "Työpaikkajaksossa on yksilöivä tunniste."}
Pitäisikö tämä kuvaus olla samalla tyylillä kuin muutkin, esim "Yksilöivä tunniste puuttuu."?

2023-08-15 12:52 UTC, pkalliok commented on src/oph/ehoks/hoks/schema.clj
> +      :description "Työpaikkajaksossa on yksilöivä tunniste."}
Toteutin nyt tuon mun ehdotuksen, katsopa kelpaako :)

2023-08-16 06:43 UTC, tomikat approved these changes
Mainio parannus virheviesteihin, tuo muoto opastaa paljon selkeämmin käyttäjiä!

2023-08-16 08:13 UTC, pkalliok commented
Laitan tän nyt taas testiympäristöön.

2023-08-17 08:27 UTC, pkalliok commented
Testattu:
```
# onnistuu (koska OHT ei ole työpaikkajakso):
atehwa@polokku:~/proj/ehoks$ sh scripts/curl-with-cas.sh -H 'Content-type: application/json' https://virkailija.testiopintopolku.fi/ehoks-virkailija-backend/api/v1/hoks/44910 -X PUT -d '{"id": 44910, "opiskeluoikeus-oid": "1.2.246.562.15.49246005745", "oppija-oid": "1.2.246.562.24.40818434200", "ensikertainen-hyvaksyminen": "2023-08-23", "osaamisen-hankkimisen-tarve": true, "hankittavat-ammat-tutkinnon-osat": [{"tutkinnon-osa-koodi-uri": "tutkinnonosat_098543", "tutkinnon-osa-koodi-versio": 1, "osaamisen-hankkimistavat": [{"alku": "2023-08-01", "loppu": "2023-08-30", "osaamisen-hankkimistapa-koodi-uri": "osaamisenhankkimistapa_000001", "osaamisen-hankkimistapa-koodi-versio": 1}]}]}' | jq .body,.errors; echo

# epäonnistuu
atehwa@polokku:~/proj/ehoks$ sh scripts/curl-with-cas.sh -H 'Content-type: application/json' https://virkailija.testiopintopolku.fi/ehoks-virkailija-backend/api/v1/hoks/44910 -X PUT -d '{"id": 44910, "opiskeluoikeus-oid": "1.2.246.562.15.49246005745", "oppija-oid": "1.2.246.562.24.40818434200", "ensikertainen-hyvaksyminen": "2023-08-23", "osaamisen-hankkimisen-tarve": true, "hankittavat-ammat-tutkinnon-osat": [{"tutkinnon-osa-koodi-uri": "tutkinnonosat_098543", "tutkinnon-osa-koodi-versio": 1, "osaamisen-hankkimistavat": [{"alku": "2023-08-01", "loppu": "2023-08-30", "osaamisen-hankkimistapa-koodi-uri": "osaamisenhankkimistapa_koulutussopimus", "osaamisen-hankkimistapa-koodi-versio": 1}]}]}' | jq .body,.errors; echo
null
{
  "hankittavat-ammat-tutkinnon-osat": [
    {
      "osaamisen-hankkimistavat": [
        "(not (\"Lisää osa-aikaisuustieto, joka on välillä 1-100.\" a-clojure.lang.PersistentArrayMap))"
      ]
    }
  ]
}

# epäonnistuu koska ei ole yksilöivää tunnistetta
atehwa@polokku:~/proj/ehoks$ sh scripts/curl-with-cas.sh -H 'Content-type: application/json' https://virkailija.testiopintopolku.fi/ehoks-virkailija-backend/api/v1/hoks/44910 -X PUT -d '{"id": 44910, "opiskeluoikeus-oid": "1.2.246.562.15.49246005745", "oppija-oid": "1.2.246.562.24.40818434200", "ensikertainen-hyvaksyminen": "2023-08-23", "osaamisen-hankkimisen-tarve": true, "hankittavat-ammat-tutkinnon-osat": [{"tutkinnon-osa-koodi-uri": "tutkinnonosat_098543", "tutkinnon-osa-koodi-versio": 1, "osaamisen-hankkimistavat": [{"alku": "2023-08-01", "loppu": "2023-08-30", "osaamisen-hankkimistapa-koodi-uri": "osaamisenhankkimistapa_koulutussopimus", "osa-aikaisuustieto": 100, "osaamisen-hankkimistapa-koodi-versio": 1}]}]}' | jq .body,.errors; echo
null
{
  "hankittavat-ammat-tutkinnon-osat": [
    {
      "osaamisen-hankkimistavat": [
        "(not (\"Lisää työpaikkajaksoon yksilöivä tunniste.\" a-clojure.lang.PersistentArrayMap))"
      ]
    }
  ]
}

# onnistuu koska on yksilöivä tunniste
atehwa@polokku:~/proj/ehoks$ sh scripts/curl-with-cas.sh -H 'Content-type: application/json' https://virkailija.testiopintopolku.fi/ehoks-virkailija-backend/api/v1/hoks/44910 -X PUT -d '{"id": 44910, "opiskeluoikeus-oid": "1.2.246.562.15.49246005745", "oppija-oid": "1.2.246.562.24.40818434200", "ensikertainen-hyvaksyminen": "2023-08-23", "osaamisen-hankkimisen-tarve": true, "hankittavat-ammat-tutkinnon-osat": [{"tutkinnon-osa-koodi-uri": "tutkinnonosat_098543", "tutkinnon-osa-koodi-versio": 1, "osaamisen-hankkimistavat": [{"alku": "2023-08-01", "loppu": "2023-08-30", "osaamisen-hankkimistapa-koodi-uri": "osaamisenhankkimistapa_koulutussopimus", "osa-aikaisuustieto": 100, "yksiloiva-tunniste": "ootkiva", "osaamisen-hankkimistapa-koodi-versio": 1}]}]}' | jq .body,.errors; echo

```

Lisäksi Tarja Laakkonen kokeili tiedostonsiirtoa joka heillä oli epäonnistunut viime PR:ssä (koska yksilöiviä tunnisteita edellytettiin silloin kaikilta OHT:ilta) ja nyt onnistui koska niitä edellytetään vain työpaikkajaksoilta.

2023-08-17 08:29 UTC, merged