EH-1476: Audit-lokitus päivityksiä
Opetushallitus/ehoks pull request #586
Opened 2024-02-09 11:05 UTC by severij

## Kuvaus muutoksista

Siirretty auditlogger-kirjaston toiminnallisuus eHOKSiin. JSON-muutosten hakeminen on toistaiseksi ulkoistettu https://github.com/java-json-tools/json-patch kirjastolle.

Lisäilty `:audit-data`-tiedot handlereihin, joista ne on aiemmin puuttuneet.

## Muistilista PR:n tekijälle ja katselmoijille

### Ennen asettamista katselmointiin
  - [ ] Build onnistuu ilman virheitä
  - [ ] Toiminnallisuuden kattavat yksikkötestit on tehty osana PR:ia
  - [ ] PR:n sisältämät muutokset noudattavat [sovittuja koodikäytänteitä](../doc/code-guidelines.md)
  - [ ] Koodi on riittävästi dokumentoitu tai se on muuten yksiselitteistä
  - [ ] Nimet (muuttujat, funktiot, ...) kuvaavat koodia hyvin

❗ **Katselmoijat tarkastavat, että yllä mainitut kohdat toteutuvat**

### Ennen mergeämistä `master`-haaralle
  - [ ] Vähintään yksi kehittäjä on katselmoinut ja hyväksynyt muutokset
    - Jos muutoksilla voi jotain rikkoessaan olla kauaskantoiset vaikutukset, kannattaa muutokset hyväksyttää useammalla katselmoijalla
  - [ ] Katselmoijien esittämät muutosehdotukset on huomioitu
  - [ ] Muutokset on testattu QA-ympäristössä
    - [ ] Testausohje kirjoitettu
    - [ ] Testaus delegoitu OPH:lle mikäli mahdollista
  - [ ] Yli jääneet kehityskohteet on tiketöity

2024-02-16 08:47 UTC, pkalliok commented
Ennen kuin paneudun koodiin, mainitsen vielä näistä muutoksista:

> Muutokset audit-lokituksen logiikassa:
>     * HTTP PATCH -requestien tapauksessa verrataan ainoastaan kenttiä, jotka löytyvät `new-value`sta, muutoin `new-value`sta löytymättömät kentät katsottaisiin poistetuksi.

Se voisi toki olla niinkin päin, että muodostetaan new-value:ta varten se millainen mergen lopputulos oli ja verrataan sitä vanhaan.  Mutta ei oikeastaan mitään erityistä syytä yhteen tai toiseen.

>     * Jätetty pois `timestamp`-kenttä (tää on vähän turha, koska AWS:ssa jokaiseen lokitukseen lisätään aina aikaleima `@timestamp`-kenttään)
>     * muutoslistaformaatti on pysynyt suhteellisen samanlaisena, korvasin kuitenkin "fieldName" kentän nimen nimellä "path", kentän arvon ollessa polku tietorakenteen juuresta muutoksen kohteena olevaan arvoon.

Tällaisissa on aina mahdollista, että meillä (siis opintopolun ylläpidolla) on jotain infraa, joka tukeutuu siihen, että audit-lokien formaatti on juuri tietty.  En tiedä, onko vaiko eikö.  Voidaan ehkä kysellä pilvi-infralta.

2024-02-16 09:38 UTC, severij commented
> > ...
> > * Jätetty pois `timestamp`-kenttä (tää on vähän turha, koska AWS:ssa jokaiseen lokitukseen lisätään aina aikaleima `@timestamp`-kenttään)
> > * muutoslistaformaatti on pysynyt suhteellisen samanlaisena, korvasin kuitenkin "fieldName" kentän nimen nimellä "path", kentän arvon ollessa polku tietorakenteen juuresta muutoksen kohteena olevaan arvoon.
> 
> Tällaisissa on aina mahdollista, että meillä (siis opintopolun ylläpidolla) on jotain infraa, joka tukeutuu siihen, että audit-lokien formaatti on juuri tietty. En tiedä, onko vaiko eikö. Voidaan ehkä kysellä pilvi-infralta.

Tässä audit-lokeja tutkaavan `auditmonitor`-lambdan koodi: https://github.com/Opetushallitus/cloud-base/blob/master/aws/resources/auditmonitor/audit_log_monitoring_lambda.py

Tulkitsen tuosta, että boto3-kirjastoa käyttäen haetaan tietyn aikavälin lokitukset käyttäen tuota natiivia `@timestamp`-kenttää, eli tuota auditlogger-kirjaston lisäämää timestamp-kenttää ei näin ollen tarvitsisi. Täytyy toki vielä kokeilla QA:lla. `message`-kentän alta täytyy löytyä ainakin `version`, `hostname`, `applicationType`, `serviceName`, `logSeq`, `type` (**tää näköjään unohtui lisätä, eli täytyy vielä korjata**). Voi olla myös, että tuota lokituskonfiguraatiota täytyy hieman tuunata.

2024-02-16 10:25 UTC, severij commented
> ... `type` (**tää näköjään unohtui lisätä, eli täytyy vielä korjata**) ...

Korjattu commitissa https://github.com/Opetushallitus/ehoks/pull/586/commits/3b208b2a656056f4aa621d709903676eb09a8298

2024-02-16 13:18 UTC, pkalliok reviewed
Mä laitan nyt nää tulemaan, vaikka ovatkin vähän sillisalaattia.  Älä ota mitään niistä ehdottomana, kaikki ovat vaan ehdotuksia...  Ja yritän tehdä uuden review'n jossa on selkeämpiä ehdotuksia, kun nää ei oo kovin tarkasti kirjoitettuja.

2024-02-16 13:18 UTC, pkalliok commented on test/oph/ehoks/logging/audit_test.clj
> +          (is (= ahato-read (expected-log-entry-on-ahato-read @logseq))))
```suggestion
        (let [logseq (get hoks-create "logseq")]
          (is (= hoks-create (expected-log-entry-on-hoks-creation logseq)))
          (is (= ahato-creation (expected-log-entry-on-ahato-creation (+ 2 logseq))))
          (is (= ahato-update (expected-log-entry-on-ahato-update (+ 3 logseq))))
          (is (= ahato-read (expected-log-entry-on-ahato-read (+ 4 logseq)))))
```

2024-02-16 13:18 UTC, pkalliok commented on src/oph/ehoks/hoks/handler.clj
> +                   :audit-data {:old old-hpto :new values}))
Muokkaus: joo, ootkin hoitanut asian eri tasolla.  Tää mietityttää mua, koska nyt päätös siitä mitä dataa lokitetaan ja miten se lokitetaan on eri paikassa.

2024-02-16 13:18 UTC, pkalliok commented on src/oph/ehoks/logging/audit.clj
> +(defn- map-changes
tällä on vähän monitulkintainen nimi (clojuressa map tarkoittaa harmillisesti kahta ihan eri asiaa).  Ehkä hashmap-changes tjsp?

2024-02-16 13:29 UTC, pkalliok commented on resources/db/hoksit/select_one_ahato.sql
> +  osa.tarkentavat_tiedot_osaamisen_arvioija_id as osa__tarkentavat_tiedot_osaamisen_arvioija_id,
Miks nää on lisätty?  En löytänyt mitään syytä.

2024-02-16 14:14 UTC, pkalliok requested changes
Täs on näitä mun ehdotuksia koodimuutoksiksi.  En oo mitenkään vaatimassa näitä, mut jos ne vaikuttaa susta parannuksilta, niin sitten.

2024-02-16 14:14 UTC, pkalliok commented on src/oph/ehoks/logging/audit.clj
> +         :else                   (update)))])))
```suggestion
  ([old-value new-value path]
       (cond
         (and (map? old-value) (map? new-value))
         (map-changes old-value new-value path)
         (and (vector? old-value) (vector? new-value))
         (vec-changes old-value new-value path)
         :else (atom-changes old-value new-value path)))

(def atom-changes [old-value new-value path]
    (if (= old-value new-value) []
      [(cond-> {"path" (str/join "." path)}
        (some? new-value) (assoc "newValue" new-value)
        (some? old-value) (assoc "oldValue" old-value))]))

```

2024-02-16 14:14 UTC, pkalliok commented on src/oph/ehoks/logging/audit.clj
> +         (union (set (keys old-value)) (set (keys new-value))))))
```suggestion
  [old-value new-value path]
  (mapcat #(changes (get old-value %) (get new-value %) (conj path %))
         (union (set (keys old-value)) (set (keys new-value)))))
```

2024-02-16 14:14 UTC, pkalliok commented on src/oph/ehoks/logging/audit.clj
> +    (changes old-value new-value patch? (conj path i))))
```suggestion
  [old-vec new-vec path]
  (mapcat #(changes (get old-vec %) (get new-vec %) (conj path %))
    (range (max (count old-vec) (count new-vec))))
```

2024-02-16 14:14 UTC, pkalliok commented on src/oph/ehoks/logging/audit.clj
> +    (changes old-value new-value patch? (conj path i))))
Jos haluaa tehdä for:lla, niin

```suggestion
  [old-vec new-vec patch? path]
  (for [i (range (max (count old-vec) (count new-vec)))
        change (changes (get old-vec i) (get new-vec i) (conj path i)]
     change)
```

2024-02-16 14:14 UTC, pkalliok commented on src/oph/ehoks/virkailija/handler.clj
> +        (assoc (response/no-content) :audit-data {:new hoks :old old-hoks})))
```suggestion
      (let [new-hoks (db-handler (:id (:hoks request))
                          (h/add-missing-oht-yksiloiva-tunniste hoks))]
        (assoc (response/no-content) :audit-data {:new new-hoks :old old-hoks})))
```

2024-02-16 14:15 UTC, pkalliok commented
Ehkä eniten mua mietityttää se, että miten tää lokirakenne on muuttunut ja onko sillä mitään vaikutuksia.  Se on vähän vaikee varmistaa kun aiemmille audit-lokeille ei taida olla kauheesti testejä...?

2024-02-16 14:16 UTC, pkalliok commented on src/oph/ehoks/logging/audit.clj
> +   (flatten
Kirjoitin selitykset, resolvaan tän

2024-02-16 14:37 UTC, severij commented on test/oph/ehoks/logging/audit_test.clj
> +
Ei tarvitse skrollata ohi ensin suurta määrää testidataa ennen kun pääsee lukemaan itse testejä :smile: Nuo olisi toki voinut heittää omaan tiedostoonkin.

2024-02-19 07:31 UTC, severij commented on resources/db/hoksit/select_one_ahato.sql
> +  osa.tarkentavat_tiedot_osaamisen_arvioija_id as osa__tarkentavat_tiedot_osaamisen_arvioija_id,
`hoks/handler.clj`issa tutkinnon osien (ml. aiemmin hankitut) PATCH-requesteja käsittelevissä handlereissa on käytetty aiemmin `select-hankittava-XXX-tutkinnon-osa-by-id`, joka hakee ainoastaan tutkinnon osan päätason, mikä ei tietysti ole riittävä audit-lokituksen muutosten tunnistamista varten. Korvasin nuo `get-hankittava-XXX-tutkinnon-osa`-kutsuilla, jotka hakee tutkinnon osat kokonaisuudessaan. Aiemmin hankittujen tutkinnon osien tapauksessa noista kuitenkin uupuu tuo osaamisen arvioija id, joka tarvitaan PATCH-requesteja käsittelevän handlerin myöhemmässä update-kutsussa. :sweat_smile:

2024-02-19 08:20 UTC, severij commented on src/oph/ehoks/logging/audit.clj
> +    :else (str obj)))
Prewalkilla tehty versio ei näytä olevan luettavuuden tai muunkaan kannalta parempi tässä tapauksessa, koska puun solmuille täytyy kuitenkin tehdä suurin piirtein nuo samat checkit. Tein myös jännän huomion, että alla olevilla toteutuksilla prewalk-versio näyttäisi olevan n. 10x hitaampi (ei sillä, että tällä olisi kovinkaan suurta merkitystä)
```
(do
  (defn- make-json-serializable
    [obj]
    (prewalk
     #(cond
        (or (number? %) (string? %) (boolean? %) (nil? %)) %
        (coll? %) %
        (instance? Date %) (-> (.toInstant ^Date %)
                               (.atZone (ZoneOffset/UTC))
                               str)
        :else (str %))
     obj))
  (time (dotimes [n 10000] (make-json-serializable ahato-data))))

; eval (root-form): (do (defn- make-json-serializable "Make a Clojure `obj` JSON serializable. ...
; (out) "Elapsed time: 421.614711 msecs"
```

```
(do
  (defn- make-json-serializable
    [obj]
    (cond
      (or (number? obj) (string? obj) (boolean? obj) (nil? obj)) obj
      (map? obj) (zipmap (keys obj) (map make-json-serializable (vals obj)))
      (coll? obj) (map make-json-serializable obj)
      (instance? Date obj) (-> (.toInstant ^Date obj)
                               (.atZone (ZoneOffset/UTC))
                               (str))
      :else (str obj)))
  (time (dotimes [n 10000] (make-json-serializable ahato-data))))

; eval (root-form): (do (defn- make-json-serializable [obj] (cond (or (number? obj) (string? ob...
; (out) "Elapsed time: 29.515295 msecs"
```

2024-02-20 10:42 UTC, severij commented on src/oph/ehoks/hoks/handler.clj
> +                   :audit-data {:old old-hato :new values}))
Teen tiketin :)

2024-02-20 11:51 UTC, severij commented on src/oph/ehoks/hoks/handler.clj
> +                   :audit-data {:old old-hato :new values}))
Löytyy täältä: https://jira.eduuni.fi/browse/EH-1635

2024-02-20 12:16 UTC, severij commented on src/oph/ehoks/hoks/handler.clj
> +      (if-let [old-hyto (ha/get-hankittava-yhteinen-tutkinnon-osa id)]
Näköjään tuolta voi tosiaankin palautua tyhjiä mappeja, `select-hankittava-yhteinen-tutkinnon-osa-by-id`-funktiossa `(hankittava-yhteinen-tutkinnon-osa-from-sql nil)` antaa `{}`. Siinä tapauksessa myös `ha/get-hankittava-yhteinen-tutkinnon-osa`-funktiossa `when-let` on väärin, joten täytynee tuokin korjata. :thinking:

2024-02-20 12:47 UTC, severij commented on src/oph/ehoks/hoks/handler.clj
>            (assoc (response/no-content) :audit-data {:new hoks :old old-hoks}))
Korjasin `replace-hoks!`in tältä osalta

2024-02-20 13:39 UTC, severij commented on src/oph/ehoks/logging/audit.clj
> +                              "newValue" new-value)]
Tää oli tosiaan alunperin vaan pelkkä apufunktio, jolla alkuperäisestä toteutuksesta sai hieman luettavamman :) Noiden sun ehdotusten kanssa tuo on tosin entistäkin selkeämpi, eikä tuota funktiota niin ollen tarvita.

2024-02-20 13:48 UTC, severij commented
> Ehkä eniten mua mietityttää se, että miten tää lokirakenne on muuttunut ja onko sillä mitään vaikutuksia. Se on vähän vaikee varmistaa kun aiemmille audit-lokeille ei taida olla kauheesti testejä...?

Joo, ei oo juurikaan ollut aikaisemmin testejä :/ Lokirakenne ei oo muuttunut kauheasti, ja tarkistelin tosiaan, että nuo auditmonitor-lambdan tarvitsemat kentät löytyy. Testailen toki vielä QA:lla.

2024-02-20 14:18 UTC, pkalliok commented on src/oph/ehoks/hoks/handler.clj
> +            :path-params [hoks-id :- s/Int]
sekin on ihan toimiva tapa, tai ainakin pitäisi olla.  Tuon tyyppivihjeen saa muistaakseni myös tuohon requestin destrukturointikohtaan.

2024-02-20 14:20 UTC, pkalliok commented on src/oph/ehoks/logging/audit.clj
> +    :else (str obj)))
OK, sorry että lähetin sut kokeilemaan vähän turhaksi osoittautunutta tapaa :/

2024-02-20 14:21 UTC, pkalliok commented on resources/db/hoksit/select_one_ahato.sql
> +  osa.tarkentavat_tiedot_osaamisen_arvioija_id as osa__tarkentavat_tiedot_osaamisen_arvioija_id,
Örgh, en tajua vieläkään, mihin se handler käyttää sitä, mutta en toki vastusta tuon tiedon tuloa näihin.

2024-02-20 14:55 UTC, pkalliok commented on test/oph/ehoks/logging/audit_test.clj
> +
Eipä mitään, sopii mulle :)

2024-02-20 14:57 UTC, pkalliok approved these changes
Jes, hyvältä vaikuttaa <3

2024-02-21 07:59 UTC, severij commented
Testaussuunnitelmaa (TODO):

Käynnistys ja heartbeat:
- [x] Tulee lokitus tyypillä `"alive"`, jossa `"message": "started"`
- [ ] 10 min välein tulee lokitus tyypillä `"alive"`, jossa `"message": "alive"`

Virkailijan käyttöliittymästä:

- Kaikissa:
  - [ ] `user.oid` ja `user.ipAddress` tallentuu joka operaatiossa
- Luku:
- Muokkaus
- Poisto

HOKS-rajapinnasta:
...

2024-02-28 18:15 UTC, severij commented
Mietin tässä, että onkohan `heratepalvelu`-rajapinnan endpointtien tapauksessa kuitenkaan tarve audit-lokitukselle? Tuon rajapinnan tapauksessa olisi varmaan hyvä idea rajata pääsy ainoastaan `heratepalvelu` palvelukäyttäjä-oidille. Tai jos satunnaisesti tarvitsee käyttää tuota rajapintaa muuhunkin, niin joku whitelistin tapainen?

2024-03-08 11:24 UTC, pkalliok commented
> Mietin tässä, että onkohan `heratepalvelu`-rajapinnan endpointtien tapauksessa tarvetta audit-lokitukselle? Tuon rajapinnan tapauksessa olisi varmaan hyvä idea rajata pääsy ainoastaan `heratepalvelu` palvelukäyttäjä-oidille. Tai jos satunnaisesti tarvitsee käyttää tuota rajapintaa muuhunkin, niin joku whitelistin tapainen?

Rajausta ei varmasti kannata tehdä OID:n perusteella koska se voi olla eri tuotannossa ja testissä ja hankaloittaa kaikkea, mutta sille voi tehdä erillisen käyttöoikeuden, ellei EHOKS-palveluun ole valmiiksi jotain sopivaa käyttöoikeutta johon voisi rajata.  Ei ehkä tän PR:n homma kuitenkaan?

2024-03-27 14:16 UTC, severij commented
# QA:lla testailua (WIP)

## Virkailija-rajapinta

<details>
  <summary>
  GET /ehoks-virkailija-backend/api/v1/virkailija/oppijat/{oppija-oid}/hoksit
  </summary>

  ## Kysely
  ```curl
  curl -X GET --header 'Accept: application/json' --header 'caller-id: severij' 'https://virkailija.testiopintopolku.fi/ehoks-virkailija-backend/api/v1/virkailija/oppijat/1.2.246.562.24.54450598189/hoksit'
  ```

  ## Tulos
  ```
  {
    "hostname": "ip-10-20-103-161.eu-west-1.compute.internal",
    "user": {
        "oid": "1.2.246.562.24.50363732049",
        "ipAddress": "212.226.154.19",
        "session": "8edfd20e-bd58-4aff-9de3-be04ee4fb9a8",
        "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    },
    "bootTime": "2024-03-27T16:07:45.996+02:00",
    "status": "succeeded",
    "applicationType": "backend",
    "operation": "read",
    "serviceName": "ehoks-virkailija",
    "changes": [],
    "logSeq": 4,
    "type": "log",
    "version": 1,
    "target": {
        "oppijaOid": "1.2.246.562.24.54450598189"
    }
}
  ```
</details>
<details>
  <summary>
  GET /ehoks-virkailija-backend/api/v1/virkailija/oppijat/{oppija-oid}/hoksit/oppilaitos/{oppilaitos-oid}
  </summary>

  ## Kysely
  ```curl
  curl -X GET --header 'Accept: application/json' --header 'caller-id: severij' 'https://virkailija.testiopintopolku.fi/ehoks-virkailija-backend/api/v1/virkailija/oppijat/1.2.246.562.24.54450598189/hoksit/oppilaitos/1.2.246.562.10.52251087186'
  ```

  ## Tulos
  ```
  {
    "hostname": "ip-10-20-103-161.eu-west-1.compute.internal",
    "user": {
        "oid": "1.2.246.562.24.50363732049",
        "ipAddress": "212.226.154.19",
        "session": "8edfd20e-bd58-4aff-9de3-be04ee4fb9a8",
        "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    },
    "bootTime": "2024-03-27T16:12:41.907+02:00",
    "status": "succeeded",
    "applicationType": "backend",
    "operation": "read",
    "serviceName": "ehoks-virkailija",
    "changes": [],
    "logSeq": 19,
    "type": "log",
    "version": 1,
    "target": {
        "oppijaOid": "1.2.246.562.24.54450598189",
        "oppilaitosOid": "1.2.246.562.10.52251087186"
    }
}
  ```
</details>

2024-04-04 16:09 UTC, severij commented
Olinkin näköjään tuossa refaktorointien erottelu tohinassa unohtanut siirtää tuon `wrap-hoks` middlewaren `audit/wrap-logger` mw:n edelle, mistä syystä nuo target-tiedot eivät olleet taltioituneet `request`iin. Korjasin tuon viimeisimmässä commitissa ja testailen vielä huomenna, että audit-lokitus toimii noissa :warning:-keisseissä OK.

2024-04-04 22:20 UTC, pkalliok commented on src/oph/ehoks/virkailija/handler.clj
> +      (assoc
Muutin mieleni myöhemmin; monessa kohtaa sama tarve, ehkä tää on kumminkin siistein tapa, ja on hyvä että se on yhtenäisesti.

2024-04-04 22:24 UTC, pkalliok commented
ainiin nuo testaushuomiot ovat hyviä ja osa vaatinee tiketöintiä.

2024-04-05 11:18 UTC, severij commented
`wrap-hoks` mw:n siirrot myötä alkoi toimia kaikki paitsi
* GET /ehoks-virkailija-backend/api/v1/virkailija/oppijat/{oppija-oid}/hoksit
* GET /ehoks-virkailija-backend/api/v1/virkailija/missing-oo-hoksit/{oppilaitos-oid}

Yritän saada nuo vielä toimimaan.

2024-04-10 06:24 UTC, merged